### ISSUE TITLE
Automatic deploy via GitHub often fails

### ISSUE THREAD

**Issue by TECHMAUS** [TECHMAUS/devierdedimensie.nl#2]
Returning with the following error 
```
gatsby-plugin-purgecss: Only processing  /zeit/13574e7b/src/css/style.css
--
06:28:18 PM | failed Building production JavaScript and CSS bundles - 16.875s
06:28:18 PM | ERROR #98123  WEBPACK
06:28:18 PM | Generating JavaScript bundles failed
06:28:18 PM | Can't resolve '../../public/static/d/1582510487.json' in '/zeit/13574e7b/src/components'
06:28:18 PM | File: src/components/seo.js
06:28:19 PM | not finished run queries - 16.988s
06:28:19 PM | npm ERR! code ELIFECYCLE
06:28:19 PM | npm ERR! errno 1
06:28:19 PM | npm ERR! xxiv-memories@0.3.0 build: `gatsby build`
06:28:19 PM | npm ERR! Exit status 1
06:28:19 PM | npm ERR!
06:28:19 PM | npm ERR! Failed at the xxiv-memories@0.3.0 build script.
06:28:19 PM | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
06:28:19 PM | npm ERR! A complete log of this run can be found in:
06:28:19 PM | npm ERR!     /zeit/.npm/_logs/2020-01-03T17_28_19_201Z-debug.log
06:28:19 PM | Error: Exited with 1
06:28:19 PM | at ChildProcess.child.on (/zeit/f51a0a4251865668/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:34567:24)
06:28:19 PM | at emitTwo (events.js:126:13)
06:28:19 PM | at ChildProcess.emit (events.js:214:7)
06:28:19 PM | at maybeClose (internal/child_process.js:925:16)
06:28:19 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
06:28:19 PM | worker exited with code 20 and signal null
06:28:21 PM | done
```
https://xxiv-memories-ghudc29k5.now.sh/_logs

A manual redeploy always works. Don't know what is causing this yet. 
Mentioned file ` '../../public/static/d/1582510487.json'` is the `/components/seo.js` file. So that could be a first lead.

**Comment by TECHMAUS** [comment]
Seems to be fixed now.
